import type { Metadata } from "next";
import { Montserrat,Montserrat_Subrayada } from "next/font/google";
import "./globals.css";
import { NavBar } from "./_components/nav";
import { ThemeProvider } from "@/components/theme.provider";

const MontserraSans = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const MontserratSub = Montserrat_Subrayada({
  variable: "--font-montserrat-subrayada",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${MontserraSans.variable} ${MontserratSub.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavBar />
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
